apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    division: "field"
    org: "sa"
    keep-until: "2025-04-01"
    team: "amer-commercial"
    project: "davidcastillo"
data:
  node_env: "production"